name: Test

on:
  pull_request:
  push:
    branches: [master, staging, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: "Setup: Git checkout"
        uses: actions/checkout@v2

      - name: "Setup: Copy cached dependencies"
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: "Setup: Install dependencies"
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: "Test: Lint"
        run: yarn lint

      - name: "Test: Jest"
        run: yarn jest
